# Generated by Django 3.2.9 on 2021-11-13 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('año', models.IntegerField()),
                ('descripcion', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('mundo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('altura', models.FloatField()),
                ('actor', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='static')),
                ('descripcion', models.CharField(max_length=3000)),
                ('peliculas', models.ManyToManyField(to='StarWarsApp.Pelicula')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StarWarsApp.raza')),
            ],
        ),
    ]
