# Generated by Django 3.2.9 on 2021-11-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarWarsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='raza',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='personaje',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/images/BD'),
        ),
    ]
