# Generated by Django 3.2.9 on 2021-12-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarWarsApp', '0002_auto_20211114_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='image',
            field=models.ImageField(upload_to='static\\images'),
        ),
    ]
