# Generated by Django 3.2.9 on 2021-12-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarWarsApp', '0003_alter_personaje_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='D:\\Descargas\\StarWarsWeb\\StarWarsApp\\static\\images'),
        ),
    ]
